### ISSUE TITLE
MD-UV380: Side buttons (MONI and F1) are swapped

### ISSUE THREAD

**Issue by Nimayer** [n1zzo/OpenRTX#5]
Executing the [keyboard demo](https://github.com/n1zzo/OpenRTX/blob/master/tests/platform/print_keys.c) on the Tytera MD-UV380, I have noticed that the two side keys above and below the PTT key are swapped.

The MONI key should be the lower one (with M embossed on it) but it is swapped with the upper one.

You can test this issue by rebooting your radio in bootloader mode 
(turning on the radio while pressing the PTT and the key above it)
and flashing the keyboard demo on the radio using the following commands:
```
cp tests/platform/print_keys.c openrtx/src/main.c
meson setup --cross-file cross_arm.txt build_arm
meson compile -C build_arm openrtx_mduv380_flash
```

**Comment by silseva** [comment]
Fixed with commits  [a968504](https://github.com/n1zzo/OpenRTX/commit/a968504941a4ce6be3a5309873e5de9a951464ea) and [8f2212f](https://github.com/n1zzo/OpenRTX/commit/8f2212f8a6fe241fcd8496c31f5d49576d06add9)
